console.log(navigator.appCodeName);
document.getElementById("one").innerHTML = navigator.appCodeName;
console.log(navigator.appName);
document.getElementById("two").innerHTML = navigator.appName;
console.log(navigator.appVersion);
document.getElementById("three").innerHTML = navigator.appVersion;
console.log(navigator.cookieEnabled);
document.getElementById("four").innerHTML = navigator.cookieEnabled;
console.log(navigator.geolocation);
document.getElementById("five").innerHTML = navigator.geolocation;
console.log(navigator.language);
document.getElementById("six").innerHTML = navigator.language;
console.log(navigator.onLine);
document.getElementById("seven").innerHTML = navigator.onLine;
console.log(navigator.platform);
document.getElementById("eight").innerHTML = navigator.plataform;
console.log(navigator.product);
document.getElementById("nine").innerHTML = navigator.product;
console.log(navigator.userAgent);
document.getElementById("ten").innerHTML = navigator.userAgent;